[project]
name = "epypen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.0"
dependencies = [
    "pydantic=*",
    "typing-extensions>=4.12.2",
]
